apiVersion: v1
kind: Service
metadata:
  name: simple-bank-api-service
spec:
  selector: 
      app: simple-bank-api
  type: NodePort
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    # nodePort: 32143 minikube以Docker 形式启动会无法从外部请求，查阅资源可转为vm，还待研究