apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  namespace: his
  labels:
    app: simple-bank-api
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: registry.digitalocean.com/hjfu/simplebank:latest
        ports:
        - containerPort: 8081
        env:
            - name: DB_SOURCE
              value: >-
                postgresql://root:secret@postgre-postgresql-headless.his:5432/simple_bank?sslmode=disable
      #imagePullSecrets:
      #- name: aws-ecr